title: Sapan's Website
description: > # this means to ignore newlines until "baseurl:"
  I am a Robotics Graduate student at Worcester Polytechnic Institute.
  My research focuses on developing real-time motion planning and controls algorithms for robot navigation in dynamically-changing environments.
  I am also excited in exploiting tools from Deep Learning to enable what's beyond the conventional methods.
baseurl: 'https://sapan-ostic.github.io/' # the subpath of your site, e.g. /blog
url: "https://sapan-ostic.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
# site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Sapan Agrawal # add your name
author-img: profile.jpg # add your photo
about-author: I am a Robotics Graduate student at Worcester Polytechnic Institute. My research focuses on developing real-time motion planning and controls algorithms for robot navigation in dynamically-changing environments. I am also excited in exploiting tools from Deep Learning to enable what's beyond the conventional methods. 
# social-twitter: # add your Twitter handle
# social-facebook: # add your Facebook handle
social-github: sapan-ostic # add your Github handle
social-linkedin: sapanostic # add your Linkedin handle
social-email: ssagrawal@wpi.edu # add your Email address

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
